name: Ubuntu Build and Test

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docker/**'
      - 'traces/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docker/**'
      - 'traces/**'
      - '.vscode/**'
  workflow_dispatch:


jobs:
  ubuntu-make:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -yqq make autoconf build-essential ca-certificates pkg-config libreadline-dev gcc-arm-none-eabi libnewlib-dev qtbase5-dev libbz2-dev liblz4-dev libbluetooth-dev libpython3-dev python3 python3-dev libpython3-all-dev liblua5.4-dev liblua5.4-0 lua5.4 sed libssl-dev libgd-dev

      - name: Install Python dependencies
        run: pip install -r tools/requirements.txt

      - name: make clean
        run: make clean
      - name: platform
        run: echo "PLATFORM=PM3OTHER" > Makefile.platform
      - name: Build
        env:
          V: 1
        run: make -j$((`nproc` + 1)) all

      - name: Test
        run: make check
      - name: uploadBuild
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-output  # Artifact 名称
          path: .         # 要保存的文件或文件夹路径
